In [3]:
'''
@Author: Rashmi
@Date: 2021-10-5 18:40
@Last Modified by: Rashmi
@Last Modified time: 2021-10-5 19:09
@Title :Write a Python program to get the powers of an array values element-wise.
Note: First array elements raised to powers from second array
Expected Output:
Original array
[0 1 2 3 4 5 6]
First array elements raised to powers from second array, element-wise:
[ 0 1 8 27 64 125 216]
''' 
import numpy as np
import pandas as pd
array1 = np.arange(7)
print("Original array")
print(array1)
print("First array elements raised to powers from second array, element-wise:")
second_array = np.power(array1, 3)
print(second_array)
print("array in terms of series")
ser = pd.Series(second_array) 
print(ser)

Original array
[0 1 2 3 4 5 6]
First array elements raised to powers from second array, element-wise:
[  0   1   8  27  64 125 216]
array in terms of series
0      0
1      1
2      8
3     27
4     64
5    125
6    216
dtype: int32
