In [1]:
'''
@Author: Rashmi
@Date: 2021-10-4 14:11
@Last Modified by: Rashmi
@Last Modified time: 2021-10-3 14:31
@Title :Write a Python program to create a 3-D array with ones on a diagonal and zeros
elsewhere.
Expected Output:
[[ 1. 0. 0.]
[ 0. 1. 0.]
[ 0. 0. 1.]]]
''' 
import numpy as np
array1 = np.eye(3)   #three rows and columns
print(array1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
'''
@Author: Rashmi
@Date: 2021-10-4 14:33
@Last Modified by: Rashmi
@Last Modified time: 2021-10-4 14:
@Title :Write a Python program to create an array which looks like below array.
Expected Output:
[[ 0. 0. 0.]
[ 1. 0. 0.]
[ 1. 1. 0.]
[ 1. 1. 1.]]
'''
import numpy as np
array1 = np.array([[0, 0, 0],[1, 0, 0],[1,1,0],[1,1,1]],dtype=float)
print("array in expected format is \n",array1)

array in expected format is 
 [[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


In [3]:
'''
@Author: Rashmi
@Date: 2021-10-4 15:15
@Last Modified by: Rashmi
@Last Modified time: 2021-10-4 15:24
@Title :Write a Python program to concatenate two 2-dimensional arrays.
Expected Output:
Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]])
Expected Output:
[[ 0 1 3 0 2 4]
[ 5 7 9 6 8 10]
'''
import numpy as np
array1 = np.array([[0, 1, 3], [5, 7, 9]])
array2 = np.array([[0, 2, 4], [6, 8, 10]])
array = np.concatenate((array1, array2), 1) #column wise concatenation
print(array)
array_given = np.concatenate((array1,array2))# row wise concatenation
print(array_given)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]
[[ 0  1  3]
 [ 5  7  9]
 [ 0  2  4]
 [ 6  8 10]]


In [16]:
'''
@Author: Rashmi
@Date: 2021-10-4 15:15
@Last Modified by: Rashmi
@Last Modified time: 2021-10-4 15:24
@Title :Write a Python program to make an array immutable (read-only).
Expected Output:
Test the array is read-only or not:
Try to change the value of the first element:
Traceback (most recent call last):
File "19236bd0-0bd9-11e7-a232-c706d0968eb6.py", line 6, in
x[0] = 1
ValueError: assignment destination is read-only
'''
import numpy as np
array1 = np.zeros(10)
print(array1)
array1.flags.writeable = False           #False makes array read only
print("Test the array is read-only or not:")
print("Try to change the value of the first element:")
array1[0] = 1
print(array1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Test the array is read-only or not:
Try to change the value of the first element:
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
'''
@Author: Rashmi
@Date: 2021-10-4 15:15
@Last Modified by: Rashmi
@Last Modified time: 2021-10-4 15:24
@Title :Write a Python program to create an array of (3, 4) shape, multiply every 
element value by 3 and display the new array.
Expected Output:
Original array elements:
[[ 0 1 2 3]
[ 4 5 6 7]
[ 8 9 10 11]]
New array elements:
[[ 0 3 6 9]
[12 15 18 21]
[24 27 30 33]]
'''
import numpy as np
array1 = np.arange(12).reshape(3,4)
print("the given array",array1)
result_array = array1 * 3
print("array after multiplication by 3 \n",result_array)


the given array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
array after multiplication by 3 
 [[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


In [10]:
'''
@Author: Rashmi
@Date: 2021-10-4 15:24
@Last Modified by: Rashmi
@Last Modified time: 2021-10-4 15:51
@Title :Write a Python program to convert a NumPy array into Python list structure.
Expected Output:
Original array elements:
[[0 1]
[2 3]
[4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]
'''
import numpy as np
array1 = np.arange(6).reshape(3, 2)
print("Original array elements:")
print(array1)
print("Array to list:")
print(array1.tolist())

Original array elements:
[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


In [11]:
'''
@Author: Rashmi
@Date: 2021-10-4 15:51
@Last Modified by: Rashmi
@Last Modified time: 2021-10-4 16:09
@Title :Write a Python program to convert a NumPy array into Python list structure.
Expected Output:
Original array elements:
[ 0.26153123 0.52760141 0.5718299 0.5927067 0.7831874 0.69746349
0.35399976 0.99469633 0.0694458 0.54711478]
Print array values with precision 3:
[ 0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]
'''
import numpy as np
array1 = np.array([ 0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349,             
                    0.35399976, 0.99469633, 0.0694458, 0.54711478]) 
print("Original array elements:")
print(array1)
print("array values with precision 3:")
np.set_printoptions(precision=3)
print(array1)


Original array elements:
[0.26153123 0.52760141 0.5718299  0.5927067  0.7831874  0.69746349
 0.35399976 0.99469633 0.0694458  0.54711478]
Print array values with precision 3:
[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


In [12]:
'''
@Author: Rashmi
@Date: 2021-10-4 16:09
@Last Modified by: Rashmi
@Last Modified time: 2021-10-4 16:15
@Title :Write a Python program to suppresses the use of scientific notation for small
numbers in numpy array.
Expected Output:
Original array elements:
[ 1.60000000e-10 1.60000000e+00 1.20000000e+03 2.35000000e-01]
Print array values with precision 3:
[ 0. 1.6 1200. 0.235]
'''
import numpy as np
array1 = np.array([1.6e-10, 1.6, 1200, .235]) 
print("Original array elements:")
print(array1)
print("Print array values with precision 3:")
np.set_printoptions(suppress=True)
print(array1)

Original array elements:
[1.60e-10 1.60e+00 1.20e+03 2.35e-01]
Print array values with precision 3:
[   0.       1.6   1200.       0.235]


In [14]:
'''
@Author: Rashmi
@Date: 2021-10-4 16:15
@Last Modified by: Rashmi
@Last Modified time: 2021-10-4 16:23
@Title :Write a Python program to how to add an extra column to an numpy array.
Expected Output:
[[ 10 20 30 100]
[ 40 50 60 200]]
'''
import numpy as np
array1 = np.array([[10,20,30], [40,50,60]])
print("array one\n",array1)
array2 = np.array([[100], [200]])
print("second array\n",array2)
print("appended column")
print(np.append(array1, array2, axis=1))



array one
 [[10 20 30]
 [40 50 60]]
second array
 [[100]
 [200]]
appended column
[[ 10  20  30 100]
 [ 40  50  60 200]]


In [15]:
'''
@Author: Rashmi
@Date: 2021-10-4 16:27
@Last Modified by: Rashmi
@Last Modified time: 2021-10-4 16:34
@Title :Write a Python program to remove specific elements in a numpy array.
Expected Output:
Original array:
[ 10 20 30 40 50 60 70 80 90 100]
Delete first, fourth and fifth elements:
[ 20 30 60 70 80 90 100]
'''
import numpy as np
array1 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print("Original array:")
print(array1)
print("Delete first, fourth and fifth elements:")
new_array1 = np.delete(array1, [0,3,4])
print(new_array1)

Original array:
[ 10  20  30  40  50  60  70  80  90 100]
Delete first, fourth and fifth elements:
[ 20  30  60  70  80  90 100]
