In [1]:
'''
@Author: Rashmi
@Date: 2021-10-3 17:10
@Last Modified by: Rashmi
@Last Modified time: 2021-10-3 17:17
@Title :  Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array.
Expected Output:
Original List: [12.23, 13.32, 100, 36.32]
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]
''' 
import numpy as np
list = [12.23, 13.32, 100, 36.32]
print("Original List:",list)
onedimen = np.array(list)
print("One-dimensional NumPy array: ",onedimen)

Original List: [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array:  [ 12.23  13.32 100.    36.32]


In [2]:
'''
@Author: Rashmi
@Date: 2021-10-3 17:20
@Last Modified by: Rashmi
@Last Modified time: 2021-10-3 17:30
@Title : Create a 3x3 matrix with values ranging from 2 to 10.
''' 
import numpy as np
matrx =  np.arange(2, 11).reshape(3,3)
print(matrx)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [3]:
'''
@Author: Rashmi
@Date: 2021-10-3 17:40
@Last Modified by: Rashmi
@Last Modified time: 2021-10-3 17:50
@Title : Write a Python program to create a null vector of size 10 and update sixth 
value to 11.
''' 
import numpy as np
vector = np.zeros(10)
print(vector)
print("Update sixth value to 11")
vector[6] = 11
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [5]:

'''
@Author: Rashmi
@Date: 2021-10-3 18:10
@Last Modified by: Rashmi
@Last Modified time: 2021-10-3 18:30
@Title : Write a Python program to reverse an array (first element becomes last)
''' 
import numpy as np
original_array = np.arange(12, 38)
print("Original array:")
print(original_array)
print("Reverse array:")
original_array = original_array[::-1]
print(original_array)


Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [6]:
'''
@Author: Rashmi
@Date: 2021-10-3 18:45
@Last Modified by: Rashmi
@Last Modified time: 2021-10-3 19:20
@Title :Write a Python program to create a 2d array with 1 on 
the border and 0 inside.
''' 
import numpy as np
array1 = np.ones((5,5))
print("Original array:")
print(array1)
print("1 on the border and 0 inside in the array")
array1[1:-1,1:-1] = 0
print(array1)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
'''
@Author: Rashmi
@Date: 2021-10-3 19:20
@Last Modified by: Rashmi
@Last Modified time: 2021-10-3 19:41
@Title : Write a Python program to add a border (filled with 0's)
around an existing array.
''' 
import numpy as np
array1 = np.ones((3,3))
print("Original array:")
print(array1)
print("0 on the border and 1 inside in the array")
array1 = np.pad(array1, pad_width=1, mode='constant', constant_values=0)
print(array1)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
'''
@Author: Rashmi
@Date: 2021-10-3 19:44
@Last Modified by: Rashmi
@Last Modified time: 2021-10-3 20:13
@Title : Write a Python program to create a 8x8 matrix 
and fill it with a checkerboard pattern.
''' 
import numpy as np
array1 = np.ones((3,3))
print(array1)
print("Checkerboard pattern:")
array1 = np.zeros((8,8),dtype=int)
array1[1::2,::2] = 1
array1[::2,1::2] = 1
print(array1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [9]:
'''
@Author: Rashmi
@Date: 2021-10-3 20:13
@Last Modified by: Rashmi
@Last Modified time: 2021-10-3 20:30
@Title :Write a Python program to convert a list and tuple into arrays.
''' 
import numpy as np
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
print("List to array: ")
print(np.asarray(my_list))
my_tuple = ([8, 4, 6], [1, 2, 3])
print("Tuple to array: ")
print(np.asarray(my_tuple))


List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]


In [11]:
'''
@Author: Rashmi
@Date: 2021-10-3 20:32
@Last Modified by: Rashmi
@Last Modified time: 2021-10-3 20:45
@Title :Write a Python program to append values to the end of an array.
''' 
import numpy as np
array_given = [10, 20, 30]
print("Original array:")
print(array_given)
array_given = np.append(array_given, [[40, 50, 60], [70, 80, 90]])
print("After append values to the end of the array:")
print(array_given)

Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]


In [2]:

'''
@Author: Rashmi
@Date: 2021-10-3 20:50
@Last Modified by: Rashmi
@Last Modified time: 2021-10-3 21:15
@Title : Write a Python program to find the real and imaginary parts of an 
array of complex numbers
''' 
import numpy as np
num1 = np.sqrt([1+0j])
num2 = np.sqrt([0+1j])
print("Original array:num1 ",num1)
print("Original array:num2 ",num2)
print("Real part of the array:")
print(num1.real)
print(num2.real)
print("Imaginary part of the array:")
print(num1.imag)
print(num2.imag)

Original array:num1  [1.+0.j]
Original array:num2  [0.70710678+0.70710678j]
Real part of the array:
[1.]
[0.70710678]
Imaginary part of the array:
[0.]
[0.70710678]


In [4]:
'''
@Author: Rashmi
@Date: 2021-10-3 21:15
@Last Modified by: Rashmi
@Last Modified time: 2021-10-3 21:35
@Title :Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements.
Expected Output:
Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24
''' 
import numpy as np
array1 = np.array([15,18,20], dtype=np.float64)
print("the given array is", array1)
print("Size of the array: ", array1.size)
print("Length of one array element in bytes: ", array1.itemsize)
print("Total bytes consumed by the elements of the array: ", array1.nbytes)

the given array is [15. 18. 20.]
Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


In [5]:
'''
@Author: Rashmi
@Date: 2021-10-3 21:35
@Last Modified by: Rashmi
@Last Modified time: 2021-10-3 21:45
@Title : Write a Python program to find common values between two arrays.
Expected Output:
Array1: [ 0 10 20 40 60]
Array2: [10, 30, 40]
Common values between two arrays:
[10 40]
''' 
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


In [6]:
'''
@Author: Rashmi
@Date: 2021-10-3 21:45
@Last Modified by: Rashmi
@Last Modified time: 2021-10-3 21:51
@Title :Write a Python program to find the set difference of two arrays. The set difference
will return the sorted, unique values in array1 that are not in array2.
Expected Output:
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70, 90]
Set difference between two arrays:
[ 0 20 60 80]
''' 
import numpy as np
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("difference of array,Unique values in array1 that are not in array2:")
print(np.setdiff1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
difference of array,Unique values in array1 that are not in array2:
[ 0 20 60 80]


In [7]:
'''
@Author: Rashmi
@Date: 2021-10-3 21:45
@Last Modified by: Rashmi
@Last Modified time: 2021-10-3 21:51
@Title :Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or
will return the sorted, unique values that are in only one (not both) of the input arrays.
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]
''' 
import numpy as np
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique values that are in only one (not both) of the input arrays:")
print(np.setxor1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


In [8]:
'''
@Author: Rashmi
@Date: 2021-10-3 21:45
@Last Modified by: Rashmi
@Last Modified time: 2021-10-3 21:51
@Title :Write a Python program compare two arrays using numpy.
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
''' 
import numpy as np
array1 = np.array([1, 2])
array2 = np.array([4, 5])
print("Array1: ",array1)
print("Array2: ",array2)
print("array1 > array2")
print(np.greater(array1, array2))
print("array1 >= array2")
print(np.greater_equal(array1, array2))
print("array1 <array2")
print(np.less(array1, array2))
print("array1 <= array2")
print(np.less_equal(array1, array2))

Array1:  [1 2]
Array2:  [4 5]
array1 > array2
[False False]
array1 >= array2
[False False]
array1 <array2
[ True  True]
array1 <= array2
[ True  True]


In [9]:
'''
@Author: Rashmi
@Date: 2021-10-3 21:45
@Last Modified by: Rashmi
@Last Modified time: 2021-10-3 21:51
@Title :. Write a Python program to save a NumPy array to a text file.
''' 
import numpy as np
import os
array1 = np.arange(12).reshape(4, 3)
print("Original array:")
print(array1)
header = 'col1 col2 col3'
np.savetxt('temp.txt', array1, fmt="%d", header=header) 
print("After loading, content of the text file:")
result = np.loadtxt('temp.txt')
print(result)

Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After loading, content of the text file:
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [10]:
'''
@Author: Rashmi
@Date: 2021-10-3 21:45
@Last Modified by: Rashmi
@Last Modified time: 2021-10-3 21:51
@Title :Write a Python program to create a contiguous flattened array.
Original array:
[[10 20 30]
[20 40 50]]
New flattened array:
[10 20 30 20 40 50]
''' 
import numpy as np
array1 = np.array([[10, 20, 30], [20, 40, 50]])
print("Original array:")
print(array1)
array_flat = np.ravel(array1)
print("New flattened array:")
print(array_flat)

Original array:
[[10 20 30]
 [20 40 50]]
New flattened array:
[10 20 30 20 40 50]


In [12]:
'''
@Author: Rashmi
@Date: 2021-10-3 23:15
@Last Modified by: Rashmi
@Last Modified time: 2021-10-3 23:35
@Title :Write a Python program to change the data type of an array.
Expected Output:
[[ 2 4 6]
[ 6 8 10]]
Data type of the array x is: int32
New Type: float64
[[ 2. 4. 6.]
[ 6. 8. 10.]]
''' 
import numpy as np
array1 = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
print(array1)
print("Data type of the array is:",array1.dtype)
# Change the data type of array
array_ch = array1.astype(float)
print("New Type: ",array_ch.dtype)
print(array_ch)

[[ 2  4  6]
 [ 6  8 10]]
Data type of the array is: int32
New Type:  float64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]
